spring:
  profiles:
    active: docker

---
spring:
  profiles: docker
  application:
    name: edge-service
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    noise-service: /noise/**
    user-service: /user/**
security:
  oauth2:
    resource:
      userInfoUri: http://${DOCKER_IP:localhost}:8181/uaa/user
  ignored: /noise/**
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
---
spring:
  profiles: development
  application:
    name: edge-service
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    noise-service: /noise/**
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/uaa/user
  ignored: /public/**

